---
env:
  name: CoopNavigation-v0
  max_episode_steps: 200
  state_type: feature
  wrappers: []
  wrapper_kwargs: {}
  env_kwargs:
    N_agents: 3
    cont_acts: false
  info: ''
agent:
  DiscMADDPG: {}
  DiscMATD3:
    tgt_noise:
    tgt_noise_clip:
    pol_upd_delay: 2
seed: 42
timesteps: 5_000_000
epoch_length: 5000
eval_episodes: 10
actor_weights:
critic_weights:
gamma: 0.95
tau: 0.01
net_struc_actor:
- - 64
  - relu
- - 64
  - relu
- tanh
net_struc_critic:
- - 64
  - relu
- - 64
  - relu
- identity
optimizer: Adam
loss: MSELoss
lr_actor: 0.01
lr_critic: 0.01
buffer_length: 1_000_000
grad_rescale: false
grad_clip: false
act_start_step: 5000
upd_start_step: 5000
upd_every: 100
batch_size: 1024
device: cpu
