---
env:
  name: MMGWorld-v0
  max_episode_steps: 10_000
  state_type: feature
  wrappers: []
  wrapper_kwargs: {}
  env_kwargs:
    w_dist: 0.05
    w_head: 1.5
    w_coll: 1.0
    w_COLREG: 2.0
    w_comf: 0.3
    eval_situation: 6
    state_design: RecDQN
    pdf_traj: False
  info: ''
agent:
  DQN: {}
  DDQN: {}
  SCDQN_a:
    sc_beta: 2
  SCDQN_b:
    sc_beta: 3
  SCDQN_c:
    sc_beta: 4
  ACCDDQN_a:
    AC_K: 2
  ACCDDQN_b:
    AC_K: 3
  ACCDDQN_c:
    AC_K: 4
  BootDQN:
    K: 10
    mask_p: 1
    grad_rescale: true
  KEBootDQN_a:
    kernel: test
    kernel_param: 0.05
    K: 10
    mask_p: 1
    grad_rescale: true
  KEBootDQN_b:
    kernel: test
    kernel_param: 0.1
    K: 10
    mask_p: 1
    grad_rescale: true
  KEBootDQN_c:
    kernel: test
    kernel_param: 0.15
    K: 10
    mask_p: 1
    grad_rescale: true
  KEBootDQN_d:
    kernel: test
    kernel_param: 0.25
    K: 10
    mask_p: 1
    grad_rescale: true
  KEBootDQN_e:
    kernel: gaussian_cdf
    kernel_param: 1
    K: 10
    mask_p: 1
    grad_rescale: true
  EnsembleDQN:
    N: 5
    N_to_update: 1
  MaxMinDQN_a:
    N: 2
    N_to_update: 1
  MaxMinDQN_b:
    N: 5
    N_to_update: 1
  RecDQN: {}
  LSTMRecDQN:
    double: true
    history_length: 2
    num_obs_OS: 7
    num_obs_TS: 6
seed: 1020
timesteps: 10000000
epoch_length: 5000
eval_episodes: 1
dqn_weights:
gamma: 0.999
eps_init: 1
eps_final: 0.1
eps_decay_steps: 1000000
tgt_update_freq: 1000
net_struc:
- - 128
  - relu
- - 128
  - relu
- - 128
  - relu
- identity
optimizer: Adam
loss: MSELoss
lr: 0.0001
buffer_length: 100000
grad_rescale: false
grad_clip: false
act_start_step: 1000
upd_start_step: 1000
upd_every: 1
batch_size: 32
device: cpu
