---
env:
  name: HHOS-RiverPlanning-v0
  max_episode_steps: 100
  state_type: feature
  wrappers: []
  wrapper_kwargs: {}
  env_kwargs:
    N_TSs_max: 10
    N_TSs_random: true
    w_ye : 2.0
    w_ce : 0.5
    w_coll : 3.0
    w_rule : 3.0
    w_comf : 1.0
  info: MDP
agent:
  DDPG: {}
  TD3:
    tgt_noise: 0.2
    tgt_noise_clip: 0.5
    pol_upd_delay: 2
  LSTMDDPG:
    history_length: 2
    use_past_actions: false
  LSTMTD3:
    tgt_noise: 0.2
    tgt_noise_clip: 0.5
    pol_upd_delay: 2
    history_length: 2
    use_past_actions: false
  LSTMRecTD3:
    tgt_noise: 0.2
    tgt_noise_clip: 0.5
    pol_upd_delay: 2
    history_length: 2
    use_past_actions: false
    num_obs_OS: 14
    num_obs_TS: 7
  SAC:
    lr_temp: 0.0001
    temp_tuning: true
    init_temp: 0.2
  LSTMSAC:
    history_length: 2
    use_past_actions: false
    lr_temp: 0.0001
    temp_tuning: true
    init_temp: 0.2
  TQC:
    lr_temp: 0.0001
    temp_tuning: true
    init_temp: 0.2
    top_qs_to_drop: 10
    n_qs: 25
    n_critics: 5
seed: 12
timesteps: 2_000_000
epoch_length: 5000
eval_episodes: 3
actor_weights:
critic_weights:
gamma: 0.99
tau: 0.001
net_struc_actor:
- - 128
  - relu
- - 128
  - relu
- tanh
net_struc_critic:
- - 128
  - relu
- - 128
  - relu
- identity
optimizer: Adam
loss: MSELoss
lr_actor: 0.0001
lr_critic: 0.0001
buffer_length: 500_000
grad_clip: false
grad_rescale: false
act_start_step: 5000
upd_start_step: 5000
upd_every: 1
batch_size: 32
device: cpu
