---
env:
  name: HHOS-RiverPipeline-v0
  max_episode_steps: 10_000_000
  state_type: feature
  wrappers: []
  wrapper_kwargs: {}
  env_kwargs:
    planner_weights: 7_plan_actor.pth
    planner_safety_net: false
    base_speed: 5.0
    day: storm
    time: 08:00
    global_path_file: C:/Users/Martin Waltz/Desktop/Forschung/RL_packages/HHOS/validation scenarios/real_data/Path_HHCH.pickle
    depth_data_file: C:/Users/Martin Waltz/Desktop/Forschung/RL_packages/HHOS/validation scenarios/real_data/DepthData.pickle
    N_TSs_max: 25
  info: MDP
agent:
  DDPG: {}
  TD3:
    tgt_noise: 0.2
    tgt_noise_clip: 0.5
    pol_upd_delay: 2
  LSTMDDPG:
    history_length: 2
    use_past_actions: false
  LSTMTD3:
    tgt_noise: 0.2
    tgt_noise_clip: 0.5
    pol_upd_delay: 2
    history_length: 2
    use_past_actions: false
  LSTMRecTD3:
    tgt_noise: 0.2
    tgt_noise_clip: 0.5
    pol_upd_delay: 2
    history_length: 2
    use_past_actions: false
  SAC:
    lr_temp: 0.0001
    temp_tuning: true
    init_temp: 0.2
  LSTMSAC:
    history_length: 2
    use_past_actions: false
    lr_temp: 0.0001
    temp_tuning: true
    init_temp: 0.2
  TQC:
    lr_temp: 0.0001
    temp_tuning: true
    init_temp: 0.2
    top_qs_to_drop: 10
    n_qs: 25
    n_critics: 5
seed: 12
timesteps: 5_000_000
epoch_length: 5000
eval_episodes: 1
actor_weights: 8_follow_actor.pth
critic_weights: 8_follow_critic.pth
gamma: 0.99
tau: 0.001
net_struc_actor:
- - 128
  - relu
- - 128
  - relu
- tanh
net_struc_critic:
- - 128
  - relu
- - 128
  - relu
- identity
optimizer: Adam
loss: MSELoss
lr_actor: 0.0001
lr_critic: 0.0001
buffer_length: 500_000
grad_clip: false
grad_rescale: false
act_start_step: 5000
upd_start_step: 5000
upd_every: 1
batch_size: 32
device: cpu
